core/urls.py
from django.urls import path
from .views import IndexView, Ez2TaskView, StoreProjectView, MPMonitorView

app_name = "core"
urlpatterns = [
    path("", IndexView.as_view(), name="main"),
    path("mp-monitor-project/", MPMonitorView.as_view(), name="mp_monitor"),
    path("ez2task-project/", Ez2TaskView.as_view(), name="ez2task"),
    path("store-project/", StoreProjectView.as_view(), name="store_project"),
]

igorsimb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

# URLs that should NOT be translated
urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),  # Language switch URL
    path("__debug__/", include("debug_toolbar.urls")),
    # Django admin
    path("admin/", admin.site.urls),
    path("store/", include("store.urls")),
    path("", include("store_users.urls")),
    # change {% if request.path == "/read/blog/" ... %} in blog/templates/puput/base.html and header.html
    path("read/", include("puput.urls")),
]

# URLs that should be translated
urlpatterns += i18n_patterns(
    # User management
    path("accounts/", include("allauth.urls")),
    # Local apps
    path("", include("core.urls")),
    prefix_default_language=True,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Админ-панель"
admin.site.index_title = "Администрирование сайта"

core/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ContactForm(forms.Form):
    name = forms.CharField(label=_("Name"), required=True)
    email = forms.EmailField(label=_("Email"), required=True)
    subject = forms.CharField(label=_("Subject"), required=True)
    message = forms.CharField(label=_("Message"), widget=forms.Textarea())

core/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.translation import gettext as _
from django.views.generic import TemplateView

from core.forms import ContactForm

User = get_user_model()


class IndexView(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = ContactForm(self.request.POST or None)
        context["form"] = form

        return context

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        context = self.get_context_data()
        data = request.POST
        if form.is_valid():
            name = data.get("name")
            email = data.get("email")
            subject = data.get("subject")
            message = data.get("message")

            str_msg = f"{message}\nSent by: {name} ({email})"

            send_mail(
                subject,
                str_msg,
                email,
                ["igor.simbirtsev@gmail.com"],
            )

            messages.success(self.request, _("Email has been successfully sent"))
            return redirect("core:main")
        else:
            HttpResponse(_("Something went wrong. Please try again."))

        return render(request, "core/index.html", context)


class MPMonitorView(TemplateView):
    template_name = "core/projects/mp_monitor_project.html"


class Ez2TaskView(TemplateView):
    template_name = "core/projects/ez2task_project.html"


class StoreProjectView(TemplateView):
    template_name = "core/projects/store_project.html"

core/templates/core/partials/about.html
{% load static %}
{% load i18n %}
<!-- ======= About Section ======= -->
<section id="about" class="about">
    <div class="container">

        <div class="section-title">
            <h2>{% translate "About" %}</h2>
            <h3 class="h3">{% translate "I'm Igor Simbirtsev, a Full Stack Web Developer" %}</h3>
            <p>{% translate "I am a web developer based in Russia and I build websites to help bring companies' ideas to life. With many years of experience working in startups, I help convert a vision and an idea into meaningful and useful software products. Having the ability to transform requirements into useful applications helps me prioritize tasks, iterate fast and deliver faster. Let's see if we can work together on your next project." %}</p>
        </div>

        <div class="row">
            <div class="col-lg-4" data-aos="fade-right">
                <img src="{% static 'core/img/profile-img.jpg' %}" class="img-fluid" alt="">
            </div>
            <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
                <h3>{% translate "Backend &amp; Full Stack Django Developer." %}</h3>
                <p class="fst-italic">
                    {% translate "I use Django Rest Framework for creating backend APIs. For full stack appliations I utilize libraries like <strong>HTMX</strong> and <strong>AlpineJS</strong> to make websites fast and interactive." %}
                </p>
                <div class="row">
                    <div class="col-lg-6">
                        <ul>
                            <li>
                                <i class="bi bi-chevron-right"></i> <strong>{% translate "Name:" %}</strong> <span>{% translate "Igor Simbirtsev" %}</span>
                            </li>
                            <li>
                                <i class="bi bi-chevron-right"></i> <strong>{% translate "Age:" %}</strong> <span>39</span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <strong>{% translate "City:" %}</strong> <span>{% translate "Moscow, Russia" %}</span>
                            </li>
                            <li>
                                <span x-data="{ show: false }" @click="show = true">
                                    <i class="bi bi-chevron-right"></i>
                                    <strong>Email:</strong>
                                    <button class="btn btn-outline-primary rounded-5"
                                            x-show="!show">{% translate "Reveal" %}</button>
                                    <span x-show="show" x-transition.duration.500ms>
                                    <a href="mailto:igor.simbirtsev@gmail.com" target="_blank"
                                       title='{% translate "Will open in a new tab" %}'>
                                        igor.simbirtsev@gmail
                                    </a>
                                    </span>
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
{#                <span class="fw-bold">{% translate "Download CV" %}:</span>#}
{#                <a class="btn btn-danger pill rounded-pill px-2 ms-1 me-0"#}
{#                   href="{% static 'core/img/resume_igor_simbirtsev(RUS).pdf' %}" download target="_blank">RUS</a>#}
{#                <a class="btn btn btn-danger pill rounded-pill px-2"#}
{#                   href="{% static 'core/img/resume_igor_simbirtsev(ENG).pdf' %}" download target="_blank">ENG</a>#}
                {#                TODO: uncomment after finishing Portfolio section #}
                {#                <a class="btn btn-outline-primary rounded-5" href="#portfolio" role="button">#}
                {#                    {% translate "My Work" %}#}
                {#                </a>#}
            </div>
        </div>

    </div>
</section><!-- End About Section -->

core/templates/core/partials/contact.html
{% load widget_tweaks %}
{% load static %}
{% load i18n %}
<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
    <div class="container">

        <div class="section-title">
            <h2>{% translate "Contact" %}</h2>
            <p>{% translate "Feel free to contact me any time" %}</p>
        </div>

        <div class="row" data-aos="fade-in">

            <div class="col-lg-5 d-flex align-items-stretch">
                <div class="info">
                    <div class="address">
                        <i class="bi bi-geo-alt"></i>
                        <h4>{% translate "Location:" %}</h4>
                        <p>{% translate "Moscow, Russia" %}</p>
                    </div>

                    <div class="email">
                        <i class="bi bi-envelope"></i>
                        <h4>{% translate "Email:" %}</h4>
                        <p>
                            <span x-data="{ show: false }" @click="show = true">
                                <button class="btn btn-outline-primary rounded-5"
                                        x-show="!show">{% translate "Reveal" %}</button>
                                <span x-show="show" x-transition.duration.500ms>
                                <a class="link-dark" href="mailto:igor.simbirtsev@gmail.com" target="_blank"
                                   title='{% translate "Will open in a new tab" %}'>
                                    igor.simbirtsev@gmail
                                </a>
                                </span>
                            </span>
                        </p>
                    </div>

                    {#                    <div class="phone">#}
                    {#                        <i class="bi bi-phone"></i>#}
                    {#                        <h4>Call:</h4>#}
                    {#                        <p>+1 5589 55488 55s</p>#}
                    {#                    </div>#}

                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d577325.4392982093!2d36.8237523782205!3d55.5815181635217!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46b54afc73d4b0c9%3A0x3d44d6cc5757cf4c!2sMoscow!5e0!3m2!1sen!2sru!4v1672056520314!5m2!1sen!2sru"
                            frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>
                </div>

            </div>

            <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
                <form method="POST" class="php-email-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="form-group col-md-6">
{#                            Translators: Label for Contact form's Name field #}
                            <label for="name">{% translate "Your Name" %}</label>
                            {% render_field form.name id="name" name="name" class="form-control" %}
                            {#                            <input type="text" name="name" class="form-control" id="name" required>#}
                        </div>
                        <div class="form-group col-md-6">
                            <label for="name">{% translate "Your Email" %}</label>
                            {% render_field form.email id="email" name="email" class="form-control" %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name">{% translate "Subject" %}</label>
                        {% render_field form.subject id="subject" name="subject" class="form-control" %}
                    </div>
                    <div class="form-group">
                        <label for="name">{% translate "Message" %}</label>
                        {% render_field form.message attr+=textarea name="message" class="form-control" rows="10" %}
                    </div>
                    <div class="my-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">{% translate "Your message has been sent. Thank you!" %}</div>
                    </div>
                    <div class="text-center">
                        <button type="submit">{% translate "Send Message" %}</button>
                    </div>
                </form>
            </div>

        </div>

    </div>
</section><!-- End Contact Section -->

core/templates/core/partials/facts.html
<!-- ======= Facts Section NOT USED ======= -->
<section id="facts" class="facts">
    <div class="container">

        <div class="section-title">
            <h2>Facts</h2>
            <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint
                consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat
                sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row no-gutters">

            <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up">
                <div class="count-box">
                    <i class="bi bi-emoji-smile"></i>
                    <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1"
                          class="purecounter"></span>
                    <p><strong>Happy Clients</strong> consequuntur quae</p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up" data-aos-delay="100">
                <div class="count-box">
                    <i class="bi bi-journal-richtext"></i>
                    <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1"
                          class="purecounter"></span>
                    <p><strong>Projects</strong> adipisci atque cum quia aut</p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up" data-aos-delay="200">
                <div class="count-box">
                    <i class="bi bi-headset"></i>
                    <span data-purecounter-start="0" data-purecounter-end="1453" data-purecounter-duration="1"
                          class="purecounter"></span>
                    <p><strong>Hours Of Support</strong> aut commodi quaerat</p>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 d-md-flex align-items-md-stretch" data-aos="fade-up" data-aos-delay="300">
                <div class="count-box">
                    <i class="bi bi-people"></i>
                    <span data-purecounter-start="0" data-purecounter-end="32" data-purecounter-duration="1"
                          class="purecounter"></span>
                    <p><strong>Hard Workers</strong> rerum asperiores dolor</p>
                </div>
            </div>

        </div>

    </div>
</section><!-- End Facts Section -->

core/templates/core/partials/footer.html
<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="container">
        <div class="copyright">
{#            &copy; Copyright <strong><span>iPortfolio</span></strong>#}
        </div>
        <div class="credits"></div>
    </div>
</footer><!-- End  Footer -->

core/templates/core/partials/header.html
{% load static %}
{% load i18n %}
<!-- ======= Mobile nav toggle button ======= -->
<i class="bi bi-list mobile-nav-toggle d-xl-none bg-dark"></i>
{#<i class="fa fa-list mobile-nav-toggle d-xl-none"></i>#}

<!-- Language Switcher -->
<div class="language-switcher" role="navigation" aria-label="{% translate 'Language selection' %}">
    <form action="{% url 'set_language' %}" method="post" class="language-form">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}">
        {% get_current_language as CURRENT_LANGUAGE %}
        
        <div class="lang-toggle">
            <button type="submit" name="language" value="en" title="English"
                    class="lang-btn {% if CURRENT_LANGUAGE == 'en' %}active{% endif %}"
                    aria-label="{% translate 'Switch to English' %}"
                    {% if CURRENT_LANGUAGE == 'en' %}aria-current="true"{% endif %}>
                <span class="flag-icon flag-gb"></span> EN
            </button>
            <button type="submit" name="language" value="ru" title="Русский"
                    class="lang-btn {% if CURRENT_LANGUAGE == 'ru' %}active{% endif %}"
                    aria-label="{% translate 'Switch to Russian' %}"
                    {% if CURRENT_LANGUAGE == 'ru' %}aria-current="true"{% endif %}>
                <span class="flag-icon flag-ru"></span> RU
            </button>
        </div>
    </form>
</div>

<!-- ======= Header ======= -->
<header id="header">
    <div class="d-flex flex-column">

        <div class="profile">
            <a href="{% url 'core:main' %}#hero" class="nav-link scrollto">
                <img src="{% static 'core/img/profile-img.jpg' %}" alt="" class="img-fluid rounded-circle">
            </a>
            <h1 class="text-light"><a href="{% url 'core:main' %}#hero" class="nav-link scrollto">{% translate "Igor Simbirtsev" %}</a></h1>
            <div class="social-links mt-3 text-center">
                <a href="https://github.com/igorsimb" class="github" target="_blank">
                    <i class="bx bxl-github"></i>
                </a>
                <a href="https://vk.com/igor_simbirtsev" class="vk" target="_blank">
                    <i class="bx bxl-vk"></i>
                </a>
                <a href="https://www.linkedin.com/in/igor-simbirtsev/" class="linkedin" target="_blank">
                    <i class="bx bxl-linkedin"></i>
                </a>
            </div>
        </div>

        <nav id="navbar" class="nav-menu navbar">
            <ul>
                <li><a href="{% url 'core:main' %}#hero" class="nav-link scrollto
                {% if request.path == '/en/' or request.path == '/ru/' %}active{% endif %}"><i class="bx bx-home"></i>
                    {# Translators: main nav menu's Home link #}
                    <span>{% translate "Home" %}</span></a>
                </li>
                <li><a href="{% url 'core:main' %}#about" class="nav-link scrollto"><i class="bx bx-user"></i>
                    <span>{% translate "About" %}</span></a></li>
                <li><a href="{% url 'core:main' %}#skills" class="nav-link scrollto"><i class="bx bx-wrench"></i>
                    <span>{% translate "Skills" %}</span></a>
                </li>
                <li><a href="{% url 'core:main' %}#portfolio" class="nav-link scrollto"><i class='bx bx-code-alt'></i>
                    <span>{% translate "Portfolio" %}</span></a></li>
{#                <li><a href="#services" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Services</span></a>#}
{#                </li>#}
                <li><a href="{% url 'core:main' %}#contact" class="nav-link scrollto"><i class="bx bx-envelope"></i>
                    <span>{% translate "Contact" %}</span></a>
                </li>
                <li><a href="/read/blog/" class="nav-link scrollto {% if '/blog/' in request.path %}active{% endif %}"><i class="bx bx-book-content"></i>
                    <span>{% translate "Blog" %}</span></a>
                </li>
            </ul>
        </nav><!-- .nav-menu -->
    </div>
</header><!-- End Header -->

core/templates/core/partials/hero.html
{% load i18n %}
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex flex-column justify-content-around align-items-center">
    <div class="hero-container"></div>
    <div class="hero-container" data-aos="fade-in">
        {# Translators: Hero section's main text #}
        <h1>{% translate "Igor Simbirtsev" %}</h1>
        <p>{% translate "I'm a" %}
            <span class="typed" data-typed-items="{% translate 'Django Developer, Python Programmer' %}"></span>
        </p>
    </div>
</section><!-- End Hero -->

core/templates/core/partials/portfolio.html
{% load static %}
{% load i18n %}
<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio section-bg">
    <div class="container">

        <div class="section-title">
            <h2>{% translate "Portfolio" %}</h2>
            <p class="section-description">{% translate "Showcasing complete functional projects demonstrates what I can bring to the table. I built these project from the ground up to demonstrate my skills in front-end, back-end, security, and database development. Contact me to get a complete code walkthrough. Also, check out my" %}
                <a href="https://github.com/igorsimb"
                        target="_blank">{% translate "github page" %}</a> {% translate "to see more projects." %}</p>
        </div>

        {#        <div class="row" data-aos="fade-up">#}
        {#            <div class="col-lg-12 d-flex justify-content-center">#}
        {#                <ul id="portfolio-flters">#}
        {#                    <li data-filter="*" class="filter-active">All</li>#}
        {#                    <li data-filter=".filter-app">App</li>#}
        {#                    <li data-filter=".filter-card">Card</li>#}
        {#                    <li data-filter=".filter-web">Web</li>#}
        {#                </ul>#}
        {#            </div>#}
        {#        </div>#}

        <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="100">

            {#            MP Monitor #}
            <div class="col-lg-4 col-md-6 portfolio-item filter-app">
                <div class="portfolio-wrap">
                    <img src="{% static 'core/img/portfolio/mp_monitor/main-image.png' %}"
                         class="img-fluid portfolio-img-thumbnail" alt="MP Monitor">
                    <div class="portfolio-links">
                        {# Translators: Portfolio section's title on the link to MP Monitor project page #}
                        <a href="{% url 'core:mp_monitor' %}" title="{% translate "More Details" %}"><i class="bx bx-info-circle"></i></a>
                    </div>
                </div>
            </div>

            {#            Tortiki #}
            <div class="col-lg-4 col-md-6 portfolio-item filter-app">
                <div class="portfolio-wrap">
                    <img src="{% static 'core/img/portfolio/store/tortiki_logo.jpeg' %}"
                         class="img-fluid portfolio-img-thumbnail" alt="">
                    <div class="portfolio-links">
                        <a href="{% url 'core:store_project' %}" title="{% translate "More Details" %}"><i class="bx
                        bx-info-circle"></i></a>
                    </div>
                </div>
            </div>

            {#            Ez2Task #}
            <div class="col-lg-4 col-md-6 portfolio-item filter-app">
                <div class="portfolio-wrap">
                    <img src="{% static 'core/img/portfolio/ez2task/ez2task_logo.jpg' %}"
                         class="img-fluid portfolio-img-thumbnail" alt="">
                    <div class="portfolio-links">
                        <a href="{% url 'core:ez2task' %}" title="{% translate "More Details" %}"><i class="bx bx-info-circle"></i></a>
                    </div>
                </div>
            </div>


        </div>

    </div>
</section><!-- End Portfolio Section -->

core/templates/core/partials/resume.html
<!-- ======= Resume Section NOT USED ======= -->
<section id="resume" class="resume">
    <div class="container">

        <div class="section-title">
            <h2>Resume</h2>
            <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint
                consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat
                sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">
            <div class="col-lg-6" data-aos="fade-up">
                <h3 class="resume-title">Sumary</h3>
                <div class="resume-item pb-0">
                    <h4>Alex Smith</h4>
                    <p><em>Innovative and deadline-driven Graphic Designer with 3+ years of experience designing and
                        developing user-centered digital/print marketing material from initial concept to final,
                        polished deliverable.</em></p>
                    <ul>
                        <li>Portland par 127,Orlando, FL</li>
                        <li>(123) 456-7891</li>
                        <li>alice.barkley@example.com</li>
                    </ul>
                </div>

                <h3 class="resume-title">Education</h3>
                <div class="resume-item">
                    <h4>Master of Fine Arts &amp; Graphic Design</h4>
                    <h5>2015 - 2016</h5>
                    <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
                    <p>Qui deserunt veniam. Et sed aliquam labore tempore sed quisquam iusto autem sit. Ea vero
                        voluptatum qui ut dignissimos deleniti nerada porti sand markend</p>
                </div>
                <div class="resume-item">
                    <h4>Bachelor of Fine Arts &amp; Graphic Design</h4>
                    <h5>2010 - 2014</h5>
                    <p><em>Rochester Institute of Technology, Rochester, NY</em></p>
                    <p>Quia nobis sequi est occaecati aut. Repudiandae et iusto quae reiciendis et quis Eius vel ratione
                        eius unde vitae rerum voluptates asperiores voluptatem Earum molestiae consequatur neque etlon
                        sader mart dila</p>
                </div>
            </div>
            <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">
                <h3 class="resume-title">Professional Experience</h3>
                <div class="resume-item">
                    <h4>Senior graphic design specialist</h4>
                    <h5>2019 - Present</h5>
                    <p><em>Experion, New York, NY </em></p>
                    <ul>
                        <li>Lead in the design, development, and implementation of the graphic, layout, and production
                            communication materials
                        </li>
                        <li>Delegate tasks to the 7 members of the design team and provide counsel on all aspects of the
                            project.
                        </li>
                        <li>Supervise the assessment of all graphic materials in order to ensure quality and accuracy of
                            the design
                        </li>
                        <li>Oversee the efficient use of production project budgets ranging from $2,000 - $25,000</li>
                    </ul>
                </div>
                <div class="resume-item">
                    <h4>Graphic design specialist</h4>
                    <h5>2017 - 2018</h5>
                    <p><em>Stepping Stone Advertising, New York, NY</em></p>
                    <ul>
                        <li>Developed numerous marketing programs (logos, brochures,infographics, presentations, and
                            advertisements).
                        </li>
                        <li>Managed up to 5 projects or tasks at a given time while under pressure</li>
                        <li>Recommended and consulted with clients on the most appropriate graphic design</li>
                        <li>Created 4+ design presentations and proposals a month for clients and account managers</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</section><!-- End Resume Section -->

core/templates/core/partials/services.html
<!-- ======= Services Section NOT USED======= -->
<section id="services" class="services">
    <div class="container">

        <div class="section-title">
            <h2>Services</h2>
            <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint
                consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat
                sit in iste officiis commodi quidem hic quas.</p>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
                <div class="icon"><i class="bi bi-briefcase"></i></div>
                <h4 class="title"><a href="">Lorem Ipsum</a></h4>
                <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint
                    occaecati cupiditate non provident</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="100">
                <div class="icon"><i class="bi bi-card-checklist"></i></div>
                <h4 class="title"><a href="">Dolor Sitema</a></h4>
                <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
                    commodo consequat tarad limino ata</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="200">
                <div class="icon"><i class="bi bi-bar-chart"></i></div>
                <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
                <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="300">
                <div class="icon"><i class="bi bi-binoculars"></i></div>
                <h4 class="title"><a href="">Magni Dolores</a></h4>
                <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
                    deserunt mollit anim id est laborum</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="400">
                <div class="icon"><i class="bi bi-brightness-high"></i></div>
                <h4 class="title"><a href="">Nemo Enim</a></h4>
                <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
                    praesentium voluptatum deleniti atque</p>
            </div>
            <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up" data-aos-delay="500">
                <div class="icon"><i class="bi bi-calendar4-week"></i></div>
                <h4 class="title"><a href="">Eiusmod Tempor</a></h4>
                <p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum
                    soluta nobis est eligendi</p>
            </div>
        </div>

    </div>
</section><!-- End Services Section -->

core/templates/core/partials/skills.html
{% load i18n %}
<!-- ======= Skills Section ======= -->
<section id="skills" class="skills section-bg">
    <div class="container">

        <div class="section-title">
            <h2>{% translate "Skills" %}</h2>
            <p>
                {% translate "I am a creative problem solver. I use Python, Django, SQL, Bootstrap, HTML, CSS and JavaScript. I have highlighted my key technical skills that I will bring to your project" %}.</p>
        </div>

        {% include "core/partials/skills_list.html" %}

    </div>
</section><!-- End Skills Section -->